import type { Candidate } from "./types"

export const candidates = [
  {
    id: "cand_001",
    name: "Anika Rao",
    pronouns: "she/her",
    headline: "Rust backend engineer building low-latency payments rails",
    location: "Bengaluru",
    workRights: "student-visa-sponsorship-required",
    institution: "Indian Institute of Science",
    degree: "M.Tech Computer Science",
    year: "2026",
    graduationDate: "2026-03-31",
    skills: [
      { name: "Rust", proficiency: 5, verified: true, lastEvidence: "2026-04-08" },
      { name: "PostgreSQL", proficiency: 4, verified: true, lastEvidence: "2026-03-29" },
      { name: "Distributed Systems", proficiency: 4, verified: true, lastEvidence: "2026-03-20" },
      { name: "Kafka", proficiency: 3, verified: false, lastEvidence: "2026-02-11" },
    ],
    proofBundles: [
      { id: "proof_001", role: "Backend Engineer", artifactCount: 9, freshness: "fresh", trustLevel: "employer-verified" },
      { id: "proof_002", role: "Rust Systems Engineer", artifactCount: 6, freshness: "fresh", trustLevel: "peer-endorsed" },
    ],
    readinessScore: { role: "Senior Rust Backend Engineer", score: 92, breakdown: { skills: 94, proof: 91, integrity: 96, depth: 88 } },
    githubSignal: { commits90d: 286, starredRepos: 41, languages: ["Rust", "SQL", "TypeScript"], shippedProjects: 4 },
    assessmentHistory: [
      { id: "assess_001", name: "Async ledger consistency review", score: 91, completedAt: "2026-04-03T10:20:00Z", integrityFlags: 0 },
    ],
    pipelineStage: "interview",
    tags: ["rust-backend", "payments", "high-proof", "needs-sponsorship"],
    avatarSeed: "anika-rao",
  },
  {
    id: "cand_002",
    name: "Leo McKenzie",
    pronouns: "he/him",
    headline: "Backend engineer with production Rust and event-sourced order systems",
    location: "Sydney",
    workRights: "citizen",
    institution: "University of New South Wales",
    degree: "B.E. Software Engineering",
    year: "2025",
    graduationDate: "2025-12-12",
    skills: [
      { name: "Rust", proficiency: 5, verified: true, lastEvidence: "2026-04-10" },
      { name: "Event Sourcing", proficiency: 4, verified: true, lastEvidence: "2026-03-18" },
      { name: "AWS", proficiency: 4, verified: true, lastEvidence: "2026-03-12" },
      { name: "Observability", proficiency: 3, verified: true, lastEvidence: "2026-02-27" },
    ],
    proofBundles: [
      { id: "proof_003", role: "Backend Engineer", artifactCount: 11, freshness: "fresh", trustLevel: "identity-verified" },
    ],
    readinessScore: { role: "Rust Platform Engineer", score: 89, breakdown: { skills: 90, proof: 88, integrity: 95, depth: 84 } },
    githubSignal: { commits90d: 192, starredRepos: 28, languages: ["Rust", "Go", "Terraform"], shippedProjects: 3 },
    assessmentHistory: [
      { id: "assess_002", name: "Order replay debugging task", score: 87, completedAt: "2026-03-25T03:10:00Z", integrityFlags: 0 },
    ],
    pipelineStage: "tryout",
    tags: ["rust-backend", "event-sourcing", "aws", "citizen"],
    avatarSeed: "leo-mckenzie",
  },
  {
    id: "cand_021",
    name: "Alex Morgan",
    pronouns: "they/them",
    headline: "Senior Rust engineer with backend systems proof and high-signal GitHub work",
    location: "Austin",
    workRights: "citizen",
    institution: "University of Texas at Austin",
    degree: "M.S. Computer Science",
    year: "2025",
    graduationDate: "2025-12-15",
    skills: [
      { name: "Rust", proficiency: 5, verified: true, lastEvidence: "2026-04-13" },
      { name: "Distributed Systems", proficiency: 5, verified: true, lastEvidence: "2026-04-02" },
      { name: "PostgreSQL", proficiency: 4, verified: true, lastEvidence: "2026-03-22" },
      { name: "OpenTelemetry", proficiency: 4, verified: true, lastEvidence: "2026-03-11" },
    ],
    proofBundles: [
      { id: "proof_021", role: "Backend Systems Engineer", artifactCount: 12, freshness: "fresh", trustLevel: "identity-verified" },
      { id: "proof_022", role: "Rust Backend Engineer", artifactCount: 7, freshness: "fresh", trustLevel: "employer-verified" },
    ],
    readinessScore: { role: "Senior Rust Backend Engineer", score: 88, breakdown: { skills: 91, proof: 90, integrity: 94, depth: 86 } },
    githubSignal: { commits90d: 341, starredRepos: 57, languages: ["Rust", "SQL", "Go"], shippedProjects: 5 },
    assessmentHistory: [
      { id: "assess_021", name: "Distributed ledger simulation", score: 89, completedAt: "2026-04-12T12:20:00Z", integrityFlags: 0 },
    ],
    pipelineStage: "assessment",
    tags: ["rust-backend", "distributed-systems", "github-signal", "austin"],
    avatarSeed: "alex-morgan",
  },
  {
    id: "cand_003",
    name: "Mei Tan",
    pronouns: "she/her",
    headline: "Systems programmer focused on Rust services and secure API gateways",
    location: "Singapore",
    workRights: "pr",
    institution: "National University of Singapore",
    degree: "B.Comp Information Security",
    year: "2026",
    graduationDate: "2026-01-20",
    skills: [
      { name: "Rust", proficiency: 4, verified: true, lastEvidence: "2026-04-01" },
      { name: "API Security", proficiency: 5, verified: true, lastEvidence: "2026-03-28" },
      { name: "gRPC", proficiency: 4, verified: true, lastEvidence: "2026-03-17" },
      { name: "Threat Modeling", proficiency: 4, verified: true, lastEvidence: "2026-02-22" },
    ],
    proofBundles: [
      { id: "proof_004", role: "Security Backend Engineer", artifactCount: 8, freshness: "fresh", trustLevel: "peer-endorsed" },
    ],
    readinessScore: { role: "Secure Backend Engineer", score: 86, breakdown: { skills: 87, proof: 84, integrity: 93, depth: 81 } },
    githubSignal: { commits90d: 151, starredRepos: 33, languages: ["Rust", "Python", "Shell"], shippedProjects: 2 },
    assessmentHistory: [
      { id: "assess_003", name: "Auth gateway design review", score: 84, completedAt: "2026-03-30T08:45:00Z", integrityFlags: 0 },
    ],
    pipelineStage: "assessment",
    tags: ["rust-backend", "security", "api-gateway", "pr"],
    avatarSeed: "mei-tan",
  },
  {
    id: "cand_004",
    name: "Oscar Nguyen",
    pronouns: "he/him",
    headline: "Rust and Go backend engineer shipping inventory reconciliation services",
    location: "Melbourne",
    workRights: "citizen",
    institution: "Monash University",
    degree: "B.Comp Advanced Computer Science",
    year: "2025",
    graduationDate: "2025-11-28",
    skills: [
      { name: "Rust", proficiency: 4, verified: true, lastEvidence: "2026-03-24" },
      { name: "Go", proficiency: 4, verified: true, lastEvidence: "2026-03-19" },
      { name: "Redis", proficiency: 3, verified: true, lastEvidence: "2026-02-17" },
      { name: "Domain Modeling", proficiency: 4, verified: false, lastEvidence: "2026-01-30" },
    ],
    proofBundles: [
      { id: "proof_005", role: "Backend Engineer", artifactCount: 7, freshness: "fresh", trustLevel: "employer-verified" },
    ],
    readinessScore: { role: "Backend Product Engineer", score: 82, breakdown: { skills: 83, proof: 79, integrity: 89, depth: 77 } },
    githubSignal: { commits90d: 109, starredRepos: 21, languages: ["Rust", "Go", "SQL"], shippedProjects: 3 },
    assessmentHistory: [
      { id: "assess_004", name: "Inventory race-condition fix", score: 80, completedAt: "2026-03-14T22:15:00Z", integrityFlags: 0 },
    ],
    pipelineStage: "responded",
    tags: ["rust-backend", "go", "commerce", "melbourne"],
    avatarSeed: "oscar-nguyen",
  },
  {
    id: "cand_005",
    name: "Priya Nair",
    pronouns: "she/her",
    headline: "Backend engineer with Rust, queues, and measurable reliability wins",
    location: "Toronto",
    workRights: "pr",
    institution: "University of Toronto",
    degree: "M.Eng Electrical and Computer Engineering",
    year: "2026",
    graduationDate: "2026-02-06",
    skills: [
      { name: "Rust", proficiency: 4, verified: true, lastEvidence: "2026-04-06" },
      { name: "RabbitMQ", proficiency: 4, verified: true, lastEvidence: "2026-03-09" },
      { name: "Service Reliability", proficiency: 4, verified: true, lastEvidence: "2026-02-26" },
      { name: "Kubernetes", proficiency: 3, verified: false, lastEvidence: "2026-02-03" },
    ],
    proofBundles: [
      { id: "proof_006", role: "Backend Engineer", artifactCount: 6, freshness: "fresh", trustLevel: "identity-verified" },
    ],
    readinessScore: { role: "Rust Backend Engineer", score: 84, breakdown: { skills: 85, proof: 81, integrity: 92, depth: 78 } },
    githubSignal: { commits90d: 137, starredRepos: 19, languages: ["Rust", "Python", "YAML"], shippedProjects: 2 },
    assessmentHistory: [
      { id: "assess_005", name: "Queue backpressure incident memo", score: 83, completedAt: "2026-04-07T15:00:00Z", integrityFlags: 0 },
    ],
    pipelineStage: "contacted",
    tags: ["rust-backend", "reliability", "queues", "toronto"],
    avatarSeed: "priya-nair",
  },
  {
    id: "cand_006",
    name: "Rafael Costa",
    pronouns: "he/him",
    headline: "Backend engineer turning legacy services into typed Rust boundaries",
    location: "Sydney",
    workRights: "student-visa-no-sponsorship",
    institution: "University of Technology Sydney",
    degree: "M.IT Software Development",
    year: "2025",
    graduationDate: "2025-12-05",
    skills: [
      { name: "Rust", proficiency: 4, verified: true, lastEvidence: "2026-03-31" },
      { name: "API Migration", proficiency: 4, verified: true, lastEvidence: "2026-03-15" },
      { name: "Node.js", proficiency: 3, verified: true, lastEvidence: "2026-02-12" },
      { name: "Testing", proficiency: 4, verified: true, lastEvidence: "2026-03-27" },
    ],
    proofBundles: [
      { id: "proof_007", role: "Backend Engineer", artifactCount: 5, freshness: "fresh", trustLevel: "self-attested" },
    ],
    readinessScore: { role: "Backend Migration Engineer", score: 78, breakdown: { skills: 80, proof: 72, integrity: 86, depth: 74 } },
    githubSignal: { commits90d: 88, starredRepos: 14, languages: ["Rust", "TypeScript"], shippedProjects: 2 },
    assessmentHistory: [
      { id: "assess_006", name: "Legacy API typed boundary review", score: 76, completedAt: "2026-02-28T05:30:00Z", integrityFlags: 1 },
    ],
    pipelineStage: "nurture",
    tags: ["rust-backend", "migration", "student-visa", "sydney"],
    avatarSeed: "rafael-costa",
  },
  {
    id: "cand_007",
    name: "Hannah Clarke",
    pronouns: "she/her",
    headline: "Frontend engineer shipping accessible React workflows for internal tools",
    location: "Melbourne",
    workRights: "citizen",
    institution: "RMIT University",
    degree: "B.Design Digital Media / Software Minor",
    year: "2025",
    graduationDate: "2025-12-18",
    skills: [
      { name: "React", proficiency: 5, verified: true, lastEvidence: "2026-04-09" },
      { name: "TypeScript", proficiency: 4, verified: true, lastEvidence: "2026-03-26" },
      { name: "Accessibility", proficiency: 5, verified: true, lastEvidence: "2026-03-06" },
      { name: "Design Systems", proficiency: 4, verified: true, lastEvidence: "2026-02-25" },
    ],
    proofBundles: [
      { id: "proof_008", role: "Frontend Engineer", artifactCount: 10, freshness: "fresh", trustLevel: "employer-verified" },
    ],
    readinessScore: { role: "Senior React Engineer", score: 90, breakdown: { skills: 92, proof: 88, integrity: 94, depth: 86 } },
    githubSignal: { commits90d: 174, starredRepos: 25, languages: ["TypeScript", "CSS", "MDX"], shippedProjects: 5 },
    assessmentHistory: [
      { id: "assess_007", name: "Accessible dashboard refactor", score: 90, completedAt: "2026-04-11T01:40:00Z", integrityFlags: 0 },
    ],
    pipelineStage: "offer",
    tags: ["frontend", "react", "accessibility", "design-system"],
    avatarSeed: "hannah-clarke",
  },
  {
    id: "cand_008",
    name: "Dev Patel",
    pronouns: "he/him",
    headline: "React product engineer with checkout and experimentation experience",
    location: "Bengaluru",
    workRights: "student-visa-sponsorship-required",
    institution: "PES University",
    degree: "B.Tech Computer Science",
    year: "2026",
    graduationDate: "2026-04-01",
    skills: [
      { name: "React", proficiency: 4, verified: true, lastEvidence: "2026-04-02" },
      { name: "Next.js", proficiency: 4, verified: true, lastEvidence: "2026-03-22" },
      { name: "Experimentation", proficiency: 3, verified: true, lastEvidence: "2026-03-01" },
      { name: "GraphQL", proficiency: 3, verified: false, lastEvidence: "2026-01-24" },
    ],
    proofBundles: [
      { id: "proof_009", role: "Frontend Engineer", artifactCount: 6, freshness: "fresh", trustLevel: "peer-endorsed" },
    ],
    readinessScore: { role: "Frontend Growth Engineer", score: 81, breakdown: { skills: 82, proof: 78, integrity: 88, depth: 76 } },
    githubSignal: { commits90d: 121, starredRepos: 18, languages: ["TypeScript", "JavaScript"], shippedProjects: 3 },
    assessmentHistory: [
      { id: "assess_008", name: "Checkout conversion instrumentation", score: 79, completedAt: "2026-03-16T09:05:00Z", integrityFlags: 0 },
    ],
    pipelineStage: "assessment",
    tags: ["frontend", "react", "growth", "needs-sponsorship"],
    avatarSeed: "dev-patel",
  },
  {
    id: "cand_009",
    name: "Sophie Laurent",
    pronouns: "she/her",
    headline: "Frontend engineer focused on B2B dashboards and component governance",
    location: "Toronto",
    workRights: "citizen",
    institution: "Waterloo",
    degree: "B.Math Computer Science",
    year: "2025",
    graduationDate: "2025-11-14",
    skills: [
      { name: "React", proficiency: 4, verified: true, lastEvidence: "2026-03-23" },
      { name: "TypeScript", proficiency: 4, verified: true, lastEvidence: "2026-03-23" },
      { name: "Data Visualization", proficiency: 4, verified: true, lastEvidence: "2026-02-28" },
      { name: "Testing", proficiency: 3, verified: true, lastEvidence: "2026-02-18" },
    ],
    proofBundles: [
      { id: "proof_010", role: "Frontend Engineer", artifactCount: 7, freshness: "fresh", trustLevel: "identity-verified" },
    ],
    readinessScore: { role: "React Dashboard Engineer", score: 83, breakdown: { skills: 84, proof: 82, integrity: 90, depth: 77 } },
    githubSignal: { commits90d: 97, starredRepos: 22, languages: ["TypeScript", "D3", "CSS"], shippedProjects: 2 },
    assessmentHistory: [
      { id: "assess_009", name: "Executive metrics grid exercise", score: 82, completedAt: "2026-03-09T14:35:00Z", integrityFlags: 0 },
    ],
    pipelineStage: "responded",
    tags: ["frontend", "react", "dashboards", "data-viz"],
    avatarSeed: "sophie-laurent",
  },
  {
    id: "cand_010",
    name: "Ethan Lim",
    pronouns: "he/him",
    headline: "React Native and web engineer with customer-support tooling depth",
    location: "Singapore",
    workRights: "pr",
    institution: "Singapore Management University",
    degree: "B.Sc Information Systems",
    year: "2026",
    graduationDate: "2026-02-20",
    skills: [
      { name: "React", proficiency: 4, verified: true, lastEvidence: "2026-03-29" },
      { name: "React Native", proficiency: 4, verified: true, lastEvidence: "2026-03-12" },
      { name: "Customer Ops Tooling", proficiency: 4, verified: true, lastEvidence: "2026-02-14" },
      { name: "Performance Profiling", proficiency: 3, verified: false, lastEvidence: "2026-01-19" },
    ],
    proofBundles: [
      { id: "proof_011", role: "Frontend Engineer", artifactCount: 5, freshness: "stale", trustLevel: "peer-endorsed" },
    ],
    readinessScore: { role: "Frontend Product Engineer", score: 76, breakdown: { skills: 78, proof: 70, integrity: 87, depth: 69 } },
    githubSignal: { commits90d: 64, starredRepos: 11, languages: ["TypeScript", "Swift", "Kotlin"], shippedProjects: 2 },
    assessmentHistory: [
      { id: "assess_010", name: "Support queue mobile triage prototype", score: 74, completedAt: "2026-02-22T11:20:00Z", integrityFlags: 0 },
    ],
    pipelineStage: "new",
    tags: ["frontend", "react-native", "support-tooling", "singapore"],
    avatarSeed: "ethan-lim",
  },
  {
    id: "cand_011",
    name: "Nora Ibrahim",
    pronouns: "she/her",
    headline: "ML engineer connecting product telemetry to churn-risk models",
    location: "Sydney",
    workRights: "pr",
    institution: "University of Sydney",
    degree: "M.Data Science",
    year: "2025",
    graduationDate: "2025-12-19",
    skills: [
      { name: "Python", proficiency: 5, verified: true, lastEvidence: "2026-04-04" },
      { name: "Feature Engineering", proficiency: 5, verified: true, lastEvidence: "2026-03-21" },
      { name: "Model Evaluation", proficiency: 4, verified: true, lastEvidence: "2026-03-04" },
      { name: "dbt", proficiency: 3, verified: false, lastEvidence: "2026-01-28" },
    ],
    proofBundles: [
      { id: "proof_012", role: "ML Engineer", artifactCount: 8, freshness: "fresh", trustLevel: "employer-verified" },
    ],
    readinessScore: { role: "Product ML Engineer", score: 87, breakdown: { skills: 89, proof: 85, integrity: 91, depth: 83 } },
    githubSignal: { commits90d: 118, starredRepos: 30, languages: ["Python", "SQL", "Jupyter Notebook"], shippedProjects: 3 },
    assessmentHistory: [
      { id: "assess_011", name: "Churn model error analysis", score: 88, completedAt: "2026-04-05T06:15:00Z", integrityFlags: 0 },
    ],
    pipelineStage: "interview",
    tags: ["ml", "data", "product-analytics", "sydney"],
    avatarSeed: "nora-ibrahim",
  },
  {
    id: "cand_012",
    name: "Arjun Menon",
    pronouns: "he/him",
    headline: "Data engineer with fraud-feature pipelines and warehouse modeling",
    location: "Bengaluru",
    workRights: "student-visa-no-sponsorship",
    institution: "RV College of Engineering",
    degree: "B.E. Computer Science",
    year: "2026",
    graduationDate: "2026-03-15",
    skills: [
      { name: "SQL", proficiency: 5, verified: true, lastEvidence: "2026-03-30" },
      { name: "Spark", proficiency: 4, verified: true, lastEvidence: "2026-03-10" },
      { name: "Airflow", proficiency: 4, verified: true, lastEvidence: "2026-02-19" },
      { name: "Data Contracts", proficiency: 3, verified: false, lastEvidence: "2026-01-31" },
    ],
    proofBundles: [
      { id: "proof_013", role: "Data Engineer", artifactCount: 7, freshness: "fresh", trustLevel: "peer-endorsed" },
    ],
    readinessScore: { role: "Data Platform Engineer", score: 80, breakdown: { skills: 83, proof: 77, integrity: 86, depth: 74 } },
    githubSignal: { commits90d: 76, starredRepos: 13, languages: ["Python", "SQL", "Scala"], shippedProjects: 2 },
    assessmentHistory: [
      { id: "assess_012", name: "Fraud features backfill design", score: 78, completedAt: "2026-03-18T07:50:00Z", integrityFlags: 0 },
    ],
    pipelineStage: "contacted",
    tags: ["data", "spark", "airflow", "student-visa"],
    avatarSeed: "arjun-menon",
  },
  {
    id: "cand_013",
    name: "Maya Chen",
    pronouns: "she/her",
    headline: "Applied ML builder shipping ranking experiments for marketplace search",
    location: "Toronto",
    workRights: "citizen",
    institution: "University of British Columbia",
    degree: "B.Sc Statistics and Computer Science",
    year: "2025",
    graduationDate: "2025-11-21",
    skills: [
      { name: "Ranking Systems", proficiency: 4, verified: true, lastEvidence: "2026-04-12" },
      { name: "PyTorch", proficiency: 4, verified: true, lastEvidence: "2026-03-20" },
      { name: "Experiment Analysis", proficiency: 5, verified: true, lastEvidence: "2026-03-02" },
      { name: "Feature Stores", proficiency: 3, verified: false, lastEvidence: "2026-02-02" },
    ],
    proofBundles: [
      { id: "proof_014", role: "Applied ML Engineer", artifactCount: 6, freshness: "fresh", trustLevel: "identity-verified" },
    ],
    readinessScore: { role: "Marketplace ML Engineer", score: 85, breakdown: { skills: 86, proof: 83, integrity: 90, depth: 82 } },
    githubSignal: { commits90d: 101, starredRepos: 26, languages: ["Python", "Rust", "SQL"], shippedProjects: 2 },
    assessmentHistory: [
      { id: "assess_013", name: "Search ranking offline eval", score: 86, completedAt: "2026-04-13T16:10:00Z", integrityFlags: 0 },
    ],
    pipelineStage: "tryout",
    tags: ["ml", "ranking", "marketplace", "experimentation"],
    avatarSeed: "maya-chen",
  },
  {
    id: "cand_014",
    name: "Ava Brooks",
    pronouns: "she/her",
    headline: "Product designer translating research into activation flows",
    location: "Melbourne",
    workRights: "citizen",
    institution: "Swinburne University of Technology",
    degree: "B.Design Interaction Design",
    year: "2025",
    graduationDate: "2025-12-03",
    skills: [
      { name: "Product Design", proficiency: 5, verified: true, lastEvidence: "2026-04-01" },
      { name: "User Research", proficiency: 4, verified: true, lastEvidence: "2026-03-11" },
      { name: "Design Systems", proficiency: 4, verified: true, lastEvidence: "2026-02-27" },
      { name: "Prototype Testing", proficiency: 4, verified: true, lastEvidence: "2026-02-09" },
    ],
    proofBundles: [
      { id: "proof_015", role: "Product Designer", artifactCount: 9, freshness: "fresh", trustLevel: "employer-verified" },
    ],
    readinessScore: { role: "Growth Product Designer", score: 88, breakdown: { skills: 90, proof: 86, integrity: 92, depth: 84 } },
    githubSignal: null,
    assessmentHistory: [
      { id: "assess_014", name: "Activation flow teardown", score: 89, completedAt: "2026-04-02T00:45:00Z", integrityFlags: 0 },
    ],
    pipelineStage: "interview",
    tags: ["product-design", "growth", "research", "melbourne"],
    avatarSeed: "ava-brooks",
  },
  {
    id: "cand_015",
    name: "Kiran Shah",
    pronouns: "they/them",
    headline: "Associate PM with marketplace operations and analytics proof",
    location: "Singapore",
    workRights: "student-visa-sponsorship-required",
    institution: "Nanyang Technological University",
    degree: "B.Bus Analytics",
    year: "2026",
    graduationDate: "2026-03-22",
    skills: [
      { name: "Product Analytics", proficiency: 4, verified: true, lastEvidence: "2026-03-26" },
      { name: "Roadmapping", proficiency: 3, verified: true, lastEvidence: "2026-03-08" },
      { name: "SQL", proficiency: 4, verified: true, lastEvidence: "2026-02-24" },
      { name: "Stakeholder Comms", proficiency: 4, verified: false, lastEvidence: "2026-01-26" },
    ],
    proofBundles: [
      { id: "proof_016", role: "Product Manager", artifactCount: 5, freshness: "fresh", trustLevel: "peer-endorsed" },
    ],
    readinessScore: { role: "Associate Product Manager", score: 77, breakdown: { skills: 78, proof: 73, integrity: 88, depth: 69 } },
    githubSignal: null,
    assessmentHistory: [
      { id: "assess_015", name: "Marketplace supply recovery PRD", score: 77, completedAt: "2026-03-29T04:25:00Z", integrityFlags: 0 },
    ],
    pipelineStage: "assessment",
    tags: ["product", "marketplace", "analytics", "needs-sponsorship"],
    avatarSeed: "kiran-shah",
  },
  {
    id: "cand_016",
    name: "Isabella Romano",
    pronouns: "she/her",
    headline: "UX researcher and service designer for enterprise onboarding",
    location: "Toronto",
    workRights: "pr",
    institution: "OCAD University",
    degree: "M.Des Strategic Foresight and Innovation",
    year: "2025",
    graduationDate: "2025-12-10",
    skills: [
      { name: "UX Research", proficiency: 5, verified: true, lastEvidence: "2026-03-18" },
      { name: "Service Design", proficiency: 4, verified: true, lastEvidence: "2026-03-05" },
      { name: "Journey Mapping", proficiency: 5, verified: true, lastEvidence: "2026-02-21" },
      { name: "Research Ops", proficiency: 3, verified: false, lastEvidence: "2026-01-22" },
    ],
    proofBundles: [
      { id: "proof_017", role: "Product Designer", artifactCount: 6, freshness: "stale", trustLevel: "self-attested" },
    ],
    readinessScore: { role: "Enterprise UX Researcher", score: 74, breakdown: { skills: 79, proof: 66, integrity: 84, depth: 68 } },
    githubSignal: null,
    assessmentHistory: [
      { id: "assess_016", name: "Enterprise onboarding research plan", score: 75, completedAt: "2026-02-18T13:00:00Z", integrityFlags: 0 },
    ],
    pipelineStage: "nurture",
    tags: ["product-design", "ux-research", "enterprise", "toronto"],
    avatarSeed: "isabella-romano",
  },
  {
    id: "cand_017",
    name: "Noah Singh",
    pronouns: "he/him",
    headline: "SRE intern candidate with incident reviews and Terraform modules",
    location: "Bengaluru",
    workRights: "student-visa-sponsorship-required",
    institution: "IIIT Bangalore",
    degree: "Integrated M.Tech Computer Science",
    year: "2026",
    graduationDate: "2026-04-10",
    skills: [
      { name: "Terraform", proficiency: 4, verified: true, lastEvidence: "2026-04-06" },
      { name: "Kubernetes", proficiency: 4, verified: true, lastEvidence: "2026-03-19" },
      { name: "Incident Review", proficiency: 4, verified: true, lastEvidence: "2026-03-01" },
      { name: "Prometheus", proficiency: 3, verified: true, lastEvidence: "2026-02-16" },
    ],
    proofBundles: [
      { id: "proof_018", role: "SRE", artifactCount: 8, freshness: "fresh", trustLevel: "peer-endorsed" },
    ],
    readinessScore: { role: "Junior SRE", score: 83, breakdown: { skills: 84, proof: 81, integrity: 91, depth: 76 } },
    githubSignal: { commits90d: 144, starredRepos: 17, languages: ["HCL", "Go", "Shell"], shippedProjects: 3 },
    assessmentHistory: [
      { id: "assess_017", name: "Kubernetes outage timeline", score: 84, completedAt: "2026-04-08T12:30:00Z", integrityFlags: 0 },
    ],
    pipelineStage: "tryout",
    tags: ["sre", "terraform", "kubernetes", "needs-sponsorship"],
    avatarSeed: "noah-singh",
  },
  {
    id: "cand_018",
    name: "Claire O'Neill",
    pronouns: "she/her",
    headline: "Infrastructure engineer automating secure deploy paths for regulated teams",
    location: "Sydney",
    workRights: "citizen",
    institution: "Macquarie University",
    degree: "B.Cyber Security",
    year: "2025",
    graduationDate: "2025-11-07",
    skills: [
      { name: "AWS", proficiency: 4, verified: true, lastEvidence: "2026-03-27" },
      { name: "Terraform", proficiency: 4, verified: true, lastEvidence: "2026-03-16" },
      { name: "Security Controls", proficiency: 4, verified: true, lastEvidence: "2026-02-26" },
      { name: "CI/CD", proficiency: 4, verified: true, lastEvidence: "2026-02-04" },
    ],
    proofBundles: [
      { id: "proof_019", role: "Infrastructure Engineer", artifactCount: 7, freshness: "fresh", trustLevel: "employer-verified" },
    ],
    readinessScore: { role: "Cloud Infrastructure Engineer", score: 85, breakdown: { skills: 86, proof: 84, integrity: 93, depth: 78 } },
    githubSignal: { commits90d: 82, starredRepos: 12, languages: ["HCL", "Python", "YAML"], shippedProjects: 2 },
    assessmentHistory: [
      { id: "assess_018", name: "Secure deploy pipeline review", score: 85, completedAt: "2026-03-28T02:10:00Z", integrityFlags: 0 },
    ],
    pipelineStage: "interview",
    tags: ["infra", "sre", "security", "aws"],
    avatarSeed: "claire-oneill",
  },
  {
    id: "cand_019",
    name: "Jun Park",
    pronouns: "he/him",
    headline: "Full-stack generalist bridging React workflows and Python automation",
    location: "Singapore",
    workRights: "pr",
    institution: "Singapore University of Technology and Design",
    degree: "B.Eng Computer Engineering",
    year: "2026",
    graduationDate: "2026-01-30",
    skills: [
      { name: "React", proficiency: 4, verified: true, lastEvidence: "2026-03-25" },
      { name: "Python", proficiency: 4, verified: true, lastEvidence: "2026-03-13" },
      { name: "FastAPI", proficiency: 3, verified: true, lastEvidence: "2026-02-20" },
      { name: "Product Automation", proficiency: 4, verified: false, lastEvidence: "2026-01-27" },
    ],
    proofBundles: [
      { id: "proof_020", role: "Full-stack Engineer", artifactCount: 6, freshness: "fresh", trustLevel: "identity-verified" },
    ],
    readinessScore: { role: "Full-stack Product Engineer", score: 79, breakdown: { skills: 81, proof: 76, integrity: 88, depth: 71 } },
    githubSignal: { commits90d: 93, starredRepos: 16, languages: ["TypeScript", "Python"], shippedProjects: 3 },
    assessmentHistory: [
      { id: "assess_019", name: "Ops automation workflow build", score: 78, completedAt: "2026-03-26T10:55:00Z", integrityFlags: 0 },
    ],
    pipelineStage: "contacted",
    tags: ["mixed", "full-stack", "automation", "singapore"],
    avatarSeed: "jun-park",
  },
  {
    id: "cand_020",
    name: "Talia Green",
    pronouns: "they/she",
    headline: "Product-minded engineer with design systems, analytics, and support tooling",
    location: "Toronto",
    workRights: "student-visa-sponsorship-required",
    institution: "York University",
    degree: "B.Sc Digital Media",
    year: "2026",
    graduationDate: "2026-04-15",
    skills: [
      { name: "TypeScript", proficiency: 4, verified: true, lastEvidence: "2026-04-14" },
      { name: "Design Systems", proficiency: 4, verified: true, lastEvidence: "2026-03-31" },
      { name: "Product Analytics", proficiency: 3, verified: true, lastEvidence: "2026-03-07" },
      { name: "Customer Research", proficiency: 3, verified: false, lastEvidence: "2026-02-12" },
    ],
    proofBundles: [
      { id: "proof_021", role: "Product Engineer", artifactCount: 5, freshness: "fresh", trustLevel: "peer-endorsed" },
    ],
    readinessScore: { role: "Product Engineer", score: 75, breakdown: { skills: 78, proof: 72, integrity: 83, depth: 68 } },
    githubSignal: { commits90d: 71, starredRepos: 9, languages: ["TypeScript", "CSS", "Python"], shippedProjects: 2 },
    assessmentHistory: [
      { id: "assess_020", name: "Support tooling instrumentation plan", score: 73, completedAt: "2026-04-15T18:20:00Z", integrityFlags: 1 },
    ],
    pipelineStage: "new",
    tags: ["mixed", "product-engineer", "design-system", "needs-sponsorship"],
    avatarSeed: "talia-green",
  },
] satisfies Candidate[]
