import type { OpenRole } from "./types"

export const roles = [
  {
    id: "role_001",
    title: "Senior Rust Backend Engineer",
    company: "iNGEN",
    stack: ["Rust", "PostgreSQL", "Kafka", "AWS", "OpenTelemetry"],
    mustHaves: ["Rust in production", "backend proof bundle", "database consistency experience"],
    niceToHaves: ["payments domain", "event sourcing", "service ownership"],
    rubric: [
      { dimension: "Backend depth", weight: 35, evidenceExpected: "Production service, incident review, or architecture note" },
      { dimension: "Rust fluency", weight: 30, evidenceExpected: "Reviewed Rust repository or assessment artifact" },
      { dimension: "Reliability judgment", weight: 20, evidenceExpected: "Backpressure, retry, or data consistency proof" },
      { dimension: "Communication", weight: 15, evidenceExpected: "Readable design memo or code review thread" },
    ],
    pathwayId: "path_001",
  },
  {
    id: "role_002",
    title: "Frontend Product Engineer",
    company: "iNGEN",
    stack: ["React", "TypeScript", "Next.js", "Design Systems", "Analytics"],
    mustHaves: ["React proof", "TypeScript", "accessible UI delivery"],
    niceToHaves: ["experimentation", "dashboard work", "component governance"],
    rubric: [
      { dimension: "UI execution", weight: 30, evidenceExpected: "Shipped workflow or component system" },
      { dimension: "Product judgment", weight: 25, evidenceExpected: "Experiment, metric, or support tooling artifact" },
      { dimension: "Accessibility", weight: 20, evidenceExpected: "A11y remediation or audit trail" },
      { dimension: "Code quality", weight: 25, evidenceExpected: "Typed React implementation with tests" },
    ],
    pathwayId: "path_002",
  },
  {
    id: "role_003",
    title: "Product ML Engineer",
    company: "iNGEN",
    stack: ["Python", "SQL", "PyTorch", "dbt", "Feature Pipelines"],
    mustHaves: ["model evaluation", "feature engineering", "product analytics"],
    niceToHaves: ["ranking systems", "warehouse modeling", "experimentation"],
    rubric: [
      { dimension: "Modeling discipline", weight: 30, evidenceExpected: "Evaluation report with errors and tradeoffs" },
      { dimension: "Data fluency", weight: 25, evidenceExpected: "SQL, feature pipeline, or warehouse artifact" },
      { dimension: "Product impact", weight: 25, evidenceExpected: "Metric movement or decision memo" },
      { dimension: "Integrity", weight: 20, evidenceExpected: "Reproducible notebook or peer review" },
    ],
    pathwayId: "path_003",
  },
  {
    id: "role_004",
    title: "Growth Product Designer",
    company: "iNGEN",
    stack: ["Figma", "Research", "Design Systems", "Prototyping", "Analytics"],
    mustHaves: ["activation flow proof", "research synthesis", "prototype testing"],
    niceToHaves: ["enterprise onboarding", "service design", "accessibility"],
    rubric: [
      { dimension: "Problem framing", weight: 25, evidenceExpected: "Research synthesis or opportunity map" },
      { dimension: "Interaction quality", weight: 25, evidenceExpected: "Prototype and annotated design decisions" },
      { dimension: "Evidence discipline", weight: 25, evidenceExpected: "Test plan, findings, and iteration trail" },
      { dimension: "Cross-functional clarity", weight: 25, evidenceExpected: "Handoff or PM/engineering collaboration proof" },
    ],
    pathwayId: "path_004",
  },
  {
    id: "role_005",
    title: "Cloud Infrastructure Engineer",
    company: "iNGEN",
    stack: ["AWS", "Terraform", "Kubernetes", "CI/CD", "Security Controls"],
    mustHaves: ["Terraform modules", "secure deployment proof", "incident reasoning"],
    niceToHaves: ["regulated environments", "policy as code", "observability"],
    rubric: [
      { dimension: "Infrastructure craft", weight: 35, evidenceExpected: "Reusable module or deployment artifact" },
      { dimension: "Security posture", weight: 25, evidenceExpected: "Controls map or hardening proof" },
      { dimension: "Operational judgment", weight: 25, evidenceExpected: "Incident review or rollback plan" },
      { dimension: "Documentation", weight: 15, evidenceExpected: "Runbook or maintainable README" },
    ],
    pathwayId: "path_001",
  },
  {
    id: "role_006",
    title: "Associate Product Manager",
    company: "iNGEN",
    stack: ["SQL", "Marketplaces", "Roadmapping", "Customer Research", "Experimentation"],
    mustHaves: ["clear PRD", "analytics proof", "marketplace or ops context"],
    niceToHaves: ["SQL", "support tooling", "growth loops"],
    rubric: [
      { dimension: "Structured thinking", weight: 30, evidenceExpected: "Prioritized PRD or product critique" },
      { dimension: "Analytics", weight: 25, evidenceExpected: "Metric decomposition or SQL artifact" },
      { dimension: "Customer empathy", weight: 25, evidenceExpected: "Interview notes or synthesized insights" },
      { dimension: "Execution clarity", weight: 20, evidenceExpected: "Milestone plan or launch checklist" },
    ],
    pathwayId: "path_004",
  },
] satisfies OpenRole[]
